### ISSUE TITLE
MacOS compatibility problem (pyamdgpuinfo)

### ISSUE THREAD

**Issue by jarlsondre** [HPCI-Lab/yProv4ML#4]
Hi! As this requires "pyamdgpuinfo", it does not work on MacOS at the moment. 

https://pypi.org/project/pyamdgpuinfo/

Currently, the documentation states that this library only works on Linux, making this library incompatible with MacOS.

**Comment by matbun** [comment]
I think I fixed it in https://github.com/HPCI-Lab/yProvML/pull/5

**Comment by matbun** [comment]
@lelepado01 I have updated the PR since the last was not merged. A new PR is https://github.com/HPCI-Lab/yProvML/pull/6/
